MyBlog/MyBlog.Presentation/Areas/Blog/Controllers/CategoryManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.BusinessLogicLayer.CategoryServices;
using MyBlog.Models;
using MyBlog.Presentation.Areas.Blog.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace MyBlog.Presentation.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Authorize(Roles ="Administrator, Manager")]
    public class CategoryManagerController : Controller
    {
        private readonly ICategoryServices _categoryServices;

        public CategoryManagerController(ICategoryServices categoryServices)
        {
            _categoryServices = categoryServices;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["SlugSortParm"] = sortOrder == "Slug" ? "slug_desc" : "Slug";
            ViewData["CreatedDateSortParm"] = sortOrder == "CreatedDate" ? "createdDate_desc" : "CreatedDate";
            ViewData["ModifiedDateSortParm"] = sortOrder == "ModifiedDate" ? "modifiedDate_desc" : "ModifiedDate";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Category, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = c => c.Name.Contains(searchString) || c.Slug.Contains(searchString);
            }

            Func<IQueryable<Category>, IOrderedQueryable<Category>> orderBy = null;

            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = q => q.OrderByDescending(c => c.Name);
                    break;
                case "Slug":
                    orderBy = q => q.OrderBy(c => c.Slug);
                    break;
                case "slug_desc":
                    orderBy = q => q.OrderByDescending(c => c.Slug);
                    break;
                case "CreatedDate":
                    orderBy = q => q.OrderBy(c => c.CreatedDate);
                    break;
                case "createdDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.CreatedDate);
                    break;
                case "ModifiedDate":
                    orderBy = q => q.OrderBy(c => c.ModifiedDate);
                    break;
                case "modifiedDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.ModifiedDate);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Name);
                    break;
            }

            var categories = await _categoryServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(categories);
        }

        public IActionResult Create()
        {
            var categoryViewModel = new CategoryViewModel();
            return View(categoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = categoryViewModel.Name,
                    Slug = categoryViewModel.Slug,
                    Content = categoryViewModel.Content,
                };
                try
                {
                    var result = await _categoryServices.AddAsync(category);
                    if (result > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(categoryViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoryServices.GetByIdAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            var categoryViewModel = new CategoryViewModel()
            {
                Id = category.Id,
                Slug = category.Slug,
                Name = category.Name,
                Content = category.Content,
            };

            return View(categoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    Id = categoryViewModel.Id,
                    Name = categoryViewModel.Name,
                    Slug = categoryViewModel.Slug,
                    Content = categoryViewModel.Content,
                };
                try
                {
                    var result = await _categoryServices.UpdateAsync(category);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(categoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _categoryServices.DeleteAsync(id);
                if (!result)
                {
                    return BadRequest();
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAll([FromBody] object[] selectedItems)
        {
            if (selectedItems == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _categoryServices.DeleteRangeAsync(selectedItems);
                if (!result)
                {
                    return BadRequest();
                }
                else
                {
                    return Json(result);
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

MyBlog/MyBlog.Presentation/Areas/Blog/Controllers/TagManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.BusinessLogicLayer.TagServices;
using MyBlog.Models;
using MyBlog.Presentation.Areas.Blog.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace MyBlog.Presentation.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Authorize(Roles = "Administrator, Manager")]
    public class TagManagerController : Controller
    {
        private readonly ITagServices _tagServices;

        public TagManagerController(ITagServices tagServices)
        {
            _tagServices = tagServices;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["SlugSortParm"] = sortOrder == "Slug" ? "slug_desc" : "Slug";
            ViewData["CreatedDateSortParm"] = sortOrder == "CreatedDate" ? "createdDate_desc" : "CreatedDate";
            ViewData["ModifiedDateSortParm"] = sortOrder == "ModifiedDate" ? "modifiedDate_desc" : "ModifiedDate";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Tag, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = c => c.Name.Contains(searchString) || c.Slug.Contains(searchString);
            }

            Func<IQueryable<Tag>, IOrderedQueryable<Tag>> orderBy = null;

            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = q => q.OrderByDescending(c => c.Name);
                    break;
                case "Slug":
                    orderBy = q => q.OrderBy(c => c.Slug);
                    break;
                case "slug_desc":
                    orderBy = q => q.OrderByDescending(c => c.Slug);
                    break;
                case "CreatedDate":
                    orderBy = q => q.OrderBy(c => c.CreatedDate);
                    break;
                case "createdDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.CreatedDate);
                    break;
                case "ModifiedDate":
                    orderBy = q => q.OrderBy(c => c.ModifiedDate);
                    break;
                case "modifiedDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.ModifiedDate);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Name);
                    break;
            }

            var tags = await _tagServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(tags);
        }

        public IActionResult Create()
        {
            var tagViewModel = new TagViewModel();
            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = tagViewModel.Name,
                    Slug = tagViewModel.Slug,
                    Content = tagViewModel.Content,
                };
                try
                {
                    var result = await _tagServices.AddAsync(tag);
                    if (result > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(tagViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _tagServices.GetByIdAsync(id);

            if (tag == null)
            {
                return NotFound();
            }

            var tagViewModel = new TagViewModel()
            {
                Id = tag.Id,
                Slug = tag.Slug,
                Name = tag.Name,
                Content = tag.Content,
            };

            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag()
                {
                    Id = tagViewModel.Id,
                    Name = tagViewModel.Name,
                    Slug = tagViewModel.Slug,
                    Content = tagViewModel.Content,
                };
                try
                {
                    var result = await _tagServices.UpdateAsync(tag);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _tagServices.DeleteAsync(id);
                if (!result)
                {
                    return BadRequest();
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAll([FromBody] object[] selectedItems)
        {
            if (selectedItems == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _tagServices.DeleteRangeAsync(selectedItems);
                if (!result)
                {
                    return BadRequest();
                }
                else
                {
                    return Json(result);
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

MyBlog/MyBlog.Presentation/Areas/Blog/Views/TagManager/Create.cshtml
@model TagViewModel

@{
    ViewBag.Title = "Create a new tag";
}

<div class="col-md-12">
    <h1>Create Tag</h1>
    <hr />
    <form asp-action="Create" class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" id="Name" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Slug" class="control-label"></label>
            <input asp-for="Slug" id="Slug" class="form-control" readonly="readonly" />
            <span asp-validation-for="Slug" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <input asp-for="Content" id="Content" class="form-control" />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/generateSlug.js"></script>
}

MyBlog/MyBlog.Presentation/Areas/Blog/Views/TagManager/Edit.cshtml
@model TagViewModel

@{
    ViewBag.Title = "Edit tag: " + Model.Name;
}


<div class="col-md-12">
    <h1>Edit Tag: @Model.Name</h1>
    <hr />
    <form asp-action="Edit" class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" id="TagName" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Slug" class="control-label"></label>
            <input asp-for="Slug" id="Slug" class="form-control" readonly="readonly" />
            <span asp-validation-for="Slug" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <input asp-for="Content" id="Content" class="form-control" />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/generateSlug.js"></script>
}

MyBlog/MyBlog.Presentation/Areas/Blog/Views/TagManager/Index.cshtml
@model Paginated<Tag>

@{
    ViewBag.Title = "Tag Manager";
}

<!-- Main content -->

<div class="container-fluid">
    <h3>Tag Management</h3>
    <hr />
    <section>
        <div class="heading mt-2 mb-2">
            <form asp-action="Index" asp-controller="TagManager" asp-area="Blog" method="get" class="form-inline">
                <div class="form-group mr-2">
                    <a asp-action="Create" asp-controller="CategoryManager" asp-area="Blog" class="btn btn-primary bg-custom"><i class="fas fa-plus-square"></i> Tag</a>
                </div>
                <div class="form-group">
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-danger" id="delete-all" onclick="deleteAll();"><i class="far fa-trash-alt"></i> Tag</button>
                </div>
                <div class="form-group ml-auto d-flex">
                    <select name="pageSize" id="page-size" class="custom-select mr-2">
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20">20</option>
                        <option value="30">30</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <input type="text" class="form-control mr-2" id="inputSearch" name="searchString"
                           value="@ViewData["CurrentFilter"]" placeholder="Search Tag....">
                    <button type="submit" class=" form-control btn btn-primary bg-custom mr-2">
                        <i class="fas fa-search"></i>
                    </button>
                    <a asp-action="Index" asp-controller="TagManager" asp-area="Blog" class="btn btn-secondary">
                        <i class="fas fa-undo"></i>
                    </a>
                </div>
            </form>
        </div>
        <div class="tag-list">
            <table class="table table-bordered">
                <thead class="bg-custom text-white rounded">
                    <tr>
                        <th scope="col">
                            <input type="checkbox" id="selected-all" />
                        </th>
                        <th scope="col">
                            <a asp-action="Index" asp-controller="TagManager" asp-area="Blog" asp-route-sortOrder="@ViewData["NameSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Tag Name
                            </a>
                        </th>
                        <th scope="col">
                            <a asp-action="Index" asp-controller="TagManager" asp-area="Blog" asp-route-sortOrder="@ViewData["SlugSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Slug
                            </a>
                        </th>
                        <th scope="col" class="d-none d-sm-table-cell">
                            <a asp-action="Index" asp-controller="TagManager" asp-area="Blog" asp-route-sortOrder="@ViewData["CreatedDateSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Created Date
                            </a>
                        </th>
                        <th scope="col" class="d-none d-sm-table-cell">
                            <a asp-action="Index" asp-controller="TagManager" asp-area="Blog" asp-route-sortOrder="@ViewData["ModifiedDateSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Modified Date
                            </a>
                        </th>
                        <th scope="col">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var tag in Model)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="selectedItems" class="selected-items" value="@tag.Id" />
                            </td>
                            <td scope="row">
                                <a asp-action="Edit" asp-controller="TagManager" asp-area="Blog"
                                   asp-route-id="@tag.Id">@tag.Name</a>
                            </td>
                            <td>
                                <a asp-action="Edit" asp-controller="TagManager" asp-area="Blog"
                                   asp-route-id="@tag.Id">@tag.Slug</a>
                            </td>
                            <td class="d-none d-sm-table-cell">
                                <a asp-action="Edit" asp-controller="TagManager" asp-area="Blog"
                                   asp-route-id="@tag.Id">@tag.CreatedDate.ToShortDateString()</a>
                            </td>
                            <td class="d-none d-sm-table-cell">
                                <a asp-action="Edit" asp-controller="TagManager" asp-area="Blog"
                                   asp-route-id="@tag.Id">@tag.ModifiedDate.ToShortDateString()</a>
                            </td>
                            <td>
                                <form asp-action="Delete" asp-controller="TagManager" asp-area="Blog" asp-route-id="@tag.Id">
                                    <a asp-action="Edit" asp-controller="TagManager" asp-area="Blog"
                                       asp-route-id="@tag.Id" class="btn btn-primary bg-custom">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <button type="submit"
                                            onclick="return confirm('Are you sure to delete this tag?');"
                                            class="btn btn-danger ">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            ViewBag.PageRange = 3;
        }
        <div class="paging mb-3">
            <nav aria-label="page-navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="TagManager" asp-area="Blog"
                           asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           asp-route-pageIndex="1" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="btn page-link @prevDisabled">
                            <i class="fas fa-fast-backward"></i>
                        </a>
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="TagManager" asp-area="Blog"
                           asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           asp-route-pageIndex="@(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1)" asp-route-pageSize="@ViewData["CurrentPageSize"]"
                           class="btn page-link @prevDisabled">
                            <i class="fas fa-backward"></i>
                        </a>
                    </li>

                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                        {
                            <li class="page-item">
                                <a asp-action="Index" asp-controller="TagManager" asp-area="Blog"
                                   asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                                   asp-route-pageIndex="@i" asp-route-pageSize="@ViewData["CurrentPageSize"]"
                                   class="btn page-link @(i==Model.PageIndex ? "current" : "")">
                                    @i
                                </a>
                            </li>
                        }
                    }
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="TagManager" asp-area="Blog"
                           asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           asp-route-pageIndex="@(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1)"
                           asp-route-pageSize="@ViewData["CurrentPageSize"]" class="btn page-link @nextDisabled">
                            <i class="fas fa-forward"></i>
                        </a>
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="TagManager" asp-area="Blog" asp-route-sortOrder="@ViewData["CurrentSort"]"
                           asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageIndex="@(Model.PageIndex)"
                           asp-route-pageSize="@ViewData["CurrentPageSize"]" class="btn page-link @nextDisabled">
                            <i class="fas fa-fast-forward"></i>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</div>

<!-- End main content -->

@section Scripts {
    <script>
        // Start - Page size
        var currentPageSize = @ViewData["CurrentPageSize"];
        $('#page-size').val(currentPageSize);
        // End - Page size

        // Start - Select all checkboxes
        $('#selected-all').change(function() {
            $('input:checkbox[class=selected-items]').prop('checked', this.checked);
        });
        // End - Select all checkboxes

        // Start - Enable and disable button
        var checkBoxes = $('tbody .selected-items, th #selected-all');
        checkBoxes.change(function () {
            $('#delete-all').prop('disabled', checkBoxes.filter(':checked').length < 1);
        });
        checkBoxes.change();
        // End - Enable and disable button

        // Start - Function delete all
        function deleteAll() {
            var token = $('input[type=hidden][name=__RequestVerificationToken]', document).val();
            var selectedItems = new Array();

            $('.selected-items:checkbox:checked').each(function() {
                selectedItems.push($(this).val());
            });

            $.ajax({
                url: "@Url.Action("DeleteAll", "TagManager")",
                type: "POST",
                data: JSON.stringify(selectedItems),
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                headers: { 'RequestVerificationToken': token },
                success: function (result) {
                    console.log(result);
                    $.each(selectedItems, function (key, value) {
                        console.log(value);
                        $('input:checkbox[class=selected-items]').each(function () {
                            console.log($(this));
                            if ($(this).val() == value) {
                                $(this).parent().parent().remove();
                            };
                        })
                        $('#delete-all').prop('disabled', true);
                    });
                },
                error: function(errorMessage) {
                    alert(errorMessage.responseText);
                }
            });
        }
        // End - Function delete all
    </script>
}