MyBlog/MyBlog.Presentation/Areas/Blog/Controllers/PostManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.BusinessLogicLayer.CategoryServices;
using MyBlog.BusinessLogicLayer.PostServices;
using MyBlog.BusinessLogicLayer.TagServices;
using MyBlog.Models;
using MyBlog.Presentation.Areas.Blog.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;

namespace MyBlog.Presentation.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Authorize(Roles = "Administrator, Manager")]
    public class PostManagerController : Controller
    {
        private readonly ICategoryServices _categoryServices;
        private readonly ITagServices _tagServices;
        private readonly IPostServices _postServices;

        public PostManagerController(ICategoryServices categoryServices, ITagServices tagServices, IPostServices postServices)
        {
            _categoryServices = categoryServices;
            _tagServices = tagServices;
            _postServices = postServices;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParm"] = string.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["AuthorSortParm"] = sortOrder == "Author" ? "author_desc" : "Author";
            ViewData["PublishedSortParm"] = sortOrder == "Published" ? "published_desc" : "Published";
            ViewData["PublishedDateSortParm"] = sortOrder == "PublishedDate" ? "publishedDate_desc" : "PublishedDate";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Post, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = c => c.Title.Contains(searchString) || c.Slug.Contains(searchString) || c.Author.UserName.Contains(searchString);
            }

            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;

            switch (sortOrder)
            {
                case "title_desc":
                    orderBy = q => q.OrderByDescending(c => c.Title);
                    break;
                case "Author":
                    orderBy = q => q.OrderBy(c => c.Author.UserName);
                    break;
                case "author_desc":
                    orderBy = q => q.OrderByDescending(c => c.Author.UserName);
                    break;
                case "Published":
                    orderBy = q => q.OrderBy(c => c.Published);
                    break;
                case "published_desc":
                    orderBy = q => q.OrderByDescending(c => c.Published);
                    break;
                case "PublishedDate":
                    orderBy = q => q.OrderBy(c => c.PublishedDate);
                    break;
                case "publishedDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.PublishedDate);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Title);
                    break;
            }

            var posts = await _postServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(posts);
        }

        public IActionResult Create()
        {
            var postViewModel = new PostViewModel()
            {
                //Author = User,
            };

            return View(postViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = categoryViewModel.Name,
                    Slug = categoryViewModel.Slug,
                    Content = categoryViewModel.Content,
                };
                try
                {
                    var result = await _categoryServices.AddAsync(category);
                    if (result > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(categoryViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _categoryServices.GetByIdAsync(id);

            if (category == null)
            {
                return NotFound();
            }

            var categoryViewModel = new CategoryViewModel()
            {
                Id = category.Id,
                Slug = category.Slug,
                Name = category.Name,
                Content = category.Content,
            };

            return View(categoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(CategoryViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    Id = categoryViewModel.Id,
                    Name = categoryViewModel.Name,
                    Slug = categoryViewModel.Slug,
                    Content = categoryViewModel.Content,
                };
                try
                {
                    var result = await _categoryServices.UpdateAsync(category);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(categoryViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _categoryServices.DeleteAsync(id);
                if (!result)
                {
                    return BadRequest();
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAll([FromBody] object[] selectedItems)
        {
            if (selectedItems == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _categoryServices.DeleteRangeAsync(selectedItems);
                if (!result)
                {
                    return BadRequest();
                }
                else
                {
                    return Json(result);
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

MyBlog/MyBlog.Presentation/Areas/Blog/Controllers/TagManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.BusinessLogicLayer.TagServices;
using MyBlog.Models;
using MyBlog.Presentation.Areas.Blog.ViewModels;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace MyBlog.Presentation.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Authorize(Roles = "Administrator, Manager")]
    public class TagManagerController : Controller
    {
        private readonly ITagServices _tagServices;

        public TagManagerController(ITagServices tagServices)
        {
            _tagServices = tagServices;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["SlugSortParm"] = sortOrder == "Slug" ? "slug_desc" : "Slug";
            ViewData["CreatedDateSortParm"] = sortOrder == "CreatedDate" ? "createdDate_desc" : "CreatedDate";
            ViewData["ModifiedDateSortParm"] = sortOrder == "ModifiedDate" ? "modifiedDate_desc" : "ModifiedDate";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Tag, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = c => c.Name.Contains(searchString) || c.Slug.Contains(searchString);
            }

            Func<IQueryable<Tag>, IOrderedQueryable<Tag>> orderBy = null;

            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = q => q.OrderByDescending(c => c.Name);
                    break;
                case "Slug":
                    orderBy = q => q.OrderBy(c => c.Slug);
                    break;
                case "slug_desc":
                    orderBy = q => q.OrderByDescending(c => c.Slug);
                    break;
                case "CreatedDate":
                    orderBy = q => q.OrderBy(c => c.CreatedDate);
                    break;
                case "createdDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.CreatedDate);
                    break;
                case "ModifiedDate":
                    orderBy = q => q.OrderBy(c => c.ModifiedDate);
                    break;
                case "modifiedDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.ModifiedDate);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Name);
                    break;
            }

            var tags = await _tagServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(tags);
        }

        public IActionResult Create()
        {
            var tagViewModel = new TagViewModel();
            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag()
                {
                    Id = Guid.NewGuid().ToString(),
                    Name = tagViewModel.Name,
                    Slug = tagViewModel.Slug,
                    Content = tagViewModel.Content,
                };
                try
                {
                    var result = await _tagServices.AddAsync(tag);
                    if (result > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(tagViewModel);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tag = await _tagServices.GetByIdAsync(id);

            if (tag == null)
            {
                return NotFound();
            }

            var tagViewModel = new TagViewModel()
            {
                Id = tag.Id,
                Slug = tag.Slug,
                Name = tag.Name,
                Content = tag.Content,
            };

            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag()
                {
                    Id = tagViewModel.Id,
                    Name = tagViewModel.Name,
                    Slug = tagViewModel.Slug,
                    Content = tagViewModel.Content,
                };
                try
                {
                    var result = await _tagServices.UpdateAsync(tag);
                    if (result)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
                catch (NullReferenceException)
                {
                    return NotFound();
                }
                catch (Exception)
                {
                    return BadRequest();
                }
            }
            return View(tagViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _tagServices.DeleteAsync(id);
                if (!result)
                {
                    return BadRequest();
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAll([FromBody] object[] selectedItems)
        {
            if (selectedItems == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _tagServices.DeleteRangeAsync(selectedItems);
                if (!result)
                {
                    return BadRequest();
                }
                else
                {
                    return Json(result);
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

MyBlog/MyBlog.Presentation/Views/Shared/_BlogOwner.cshtml
<div class="card">
    <img src="/images/avatar/avatar-1.png" class="card-img-top rounded-circle" alt="...">
    <div class="card-body">
        <h5 class="card-title text-center">Cong Dinh</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    </div>
    <div class="card-footer">
        <small class="text-muted">Last updated 3 mins ago</small>
    </div>
</div>

MyBlog/MyBlog.Presentation/Views/Shared/_CategoryIntro.cshtml
<div class="container-fluid category-intro">
    <div class="img-category">
        <img src="/images/logo/3797_DevBlogs_Python_hero2_DonBaker.png">
    </div>
    <div class="content-intro">
        <h1 class="intro-title">Microsoft Developer Blogs</h1>
        <p class="intro-text">Get the latest information, insights, announcements, and news from Microsoft.</p>
    </div>
</div>

MyBlog/MyBlog.Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cong Dinh</title>
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow p-0">
            <div class="container-fluid" style="width: 90%!important">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/images/logo/csharp-logo.png" width="30" height="auto" class="d-inline-block align-top" alt="">
                    Cong Dinh
                </a>
                <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <div class="dropdown-menu border-top-0 rounded-0" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Languages
                            </a>
                            <div class="dropdown-menu border-top-0 rounded-0" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                .NET
                            </a>
                            <div class="dropdown-menu border-top-0 rounded-0" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                       <partial name="_ManagerMenu" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @if (!Context.Request.Path.ToString().ToLower().Contains("blog"))
    {
        <partial name="_CategoryIntro" />
    }
    <div class="container-fluid main-content">
        <div class="row">
            @RenderBody()
            @if (!Context.Request.Path.ToString().ToLower().Contains("blog"))
            {
                <div class="col-md-3 p-0">
                    <partial name="_RightMenu" />
                </div>
            }

        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Cong Dinh - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyBlog/MyBlog.Presentation/Views/Shared/_ManagerMenu.cshtml
@if (User.Identity.IsAuthenticated && (User.IsInRole("Administrator") || User.IsInRole("Manager")))
{
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Blog Manager
        </a>
        <div class="dropdown-menu border-top-0 rounded-0" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Dashboard Manager</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-action="Index" asp-controller="CategoryManager" asp-area="Blog">Category Manager</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="TagManager" asp-area="Blog">Tag Manager</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="PostManager" asp-area="Blog">Post Manager</a>
            <a class="dropdown-item" asp-action="Index" asp-controller="CommentManager" asp-area="Blog">Comment Manager</a>
        </div>
    </li>
}

MyBlog/MyBlog.Presentation/Views/Shared/_PostOverview.cshtml
@model Post

    <div class="card box-shadow m-3">
        <div class="card-body row">
            <div class="col-md-4">
                <img src="/images/thumbnails/swimlane-cross-platform.png" class="card-img home-post">
            </div>
            <div class="col-md-8">
                <h5 class="card-title">@Model.Title</h5>
                <p class="card-text">@Model.Summary</p>
            </div>
        </div>
        <div class="card-footer mt-1 bg-white">
            <div class="row">
                <div class="col-md-4">
                    <a href="#" class="btn btn-primary rounded-0">Category<i class="fas fa-angle-right ml-2"></i></a>
                </div>
                <div class="col-md-8">

                </div>
            </div>
        </div>
    </div>

MyBlog/MyBlog.Presentation/Views/Shared/_RightMenu.cshtml
<aside class="m-3">
    <partial name="_BlogOwner"/>
</aside>