MyBlog/MyBlog.Presentation/Areas/Blog/Controllers/CommentManagerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyBlog.BusinessLogicLayer.CommentServices;
using MyBlog.Models;
using System;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

namespace MyBlog.Presentation.Areas.Blog.Controllers
{
    [Area("Blog")]
    [Authorize(Roles ="Administrator, Manager")]
    public class CommentManagerController : Controller
    {
        private readonly ICommentServices _commentServices;

        public CommentManagerController(ICommentServices commentServices)
        {
            _commentServices = commentServices;
        }

        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["ContentSortParm"] = string.IsNullOrEmpty(sortOrder) ? "content_desc" : "";
            ViewData["UsernameSortParm"] = sortOrder == "Username" ? "username_desc" : "Username";
            ViewData["PostTitleSortParm"] = sortOrder == "PostTitle" ? "postTitle_desc" : "PostTitle";
            ViewData["CreatedDateSortParm"] = sortOrder == "CreatedDate" ? "createdDate_desc" : "CreatedDate";
            ViewData["ModifiedDateSortParm"] = sortOrder == "ModifiedDate" ? "modifiedDate_desc" : "ModifiedDate";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            Expression<Func<Comment, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = c => c.Content.Contains(searchString) || c.Post.Title.Contains(searchString) || c.User.UserName.Contains(searchString);
            }

            Func<IQueryable<Comment>, IOrderedQueryable<Comment>> orderBy = null;

            switch (sortOrder)
            {
                case "content_desc":
                    orderBy = q => q.OrderByDescending(c => c.Post.Title);
                    break;
                case "Username":
                    orderBy = q => q.OrderBy(c => c.User.UserName);
                    break;
                case "username_desc":
                    orderBy = q => q.OrderByDescending(c => c.User.UserName);
                    break;
                case "PostTitle":
                    orderBy = q => q.OrderBy(c => c.Post.Title);
                    break;
                case "postTitle_desc":
                    orderBy = q => q.OrderByDescending(c => c.Post.Title);
                    break;
                case "CreatedDate":
                    orderBy = q => q.OrderBy(c => c.CreatedDate);
                    break;
                case "createdDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.CreatedDate);
                    break;
                case "ModifiedDate":
                    orderBy = q => q.OrderBy(c => c.ModifiedDate);
                    break;
                case "modifiedDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.ModifiedDate);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Post.Title);
                    break;
            }

            string includeProperties = "User,Post";

            var comments = await _commentServices.GetAsync(filter: filter, orderBy: orderBy, includeProperties: includeProperties, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(comments);
        }

        [HttpPost]
        public async Task<IActionResult> Approve(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comment = await _commentServices.GetByIdAsync(id);

            if (comment == null)
            {
                return NotFound();
            }

            comment.Approved = !comment.Approved;
            try
            {
                var result = await _commentServices.UpdateAsync(comment);
                if (result)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var result = await _commentServices.DeleteAsync(id);
                if (!result)
                {
                    return BadRequest();
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAll([FromBody] object[] selectedItems)
        {
            if (selectedItems == null)
            {
                return NotFound();
            }

            try
            {
                var x = selectedItems[0].ToString();
                var result = await _commentServices.DeleteRangeAsync(selectedItems);
                if (!result)
                {
                    return BadRequest();
                }
                else
                {
                    return Json(result);
                }
            }
            catch (NullReferenceException)
            {
                return NotFound();
            }
            catch (Exception)
            {
                return BadRequest();
            }
        }
    }
}

MyBlog/MyBlog.Presentation/Areas/Blog/Views/CommentManager/Edit.cshtml
@model CategoryViewModel

@{
    ViewBag.Title = "Edit category: " + Model.Name;
}


<div class="col-md-12">
    <h1>Edit Category: @Model.Name</h1>
    <hr />
    <form asp-action="Edit" class="form-horizontal">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" id="CategoryName" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Slug" class="control-label"></label>
            <input asp-for="Slug" id="Slug" class="form-control" readonly="readonly" />
            <span asp-validation-for="Slug" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Content" class="control-label"></label>
            <input asp-for="Content" id="Content" class="form-control" />
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Back to List</a>
        </div>
    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/generateSlug.js"></script>
}

MyBlog/MyBlog.Presentation/Areas/Blog/Views/CommentManager/Index.cshtml
@model Paginated<Comment>

@{
    ViewBag.Title = "Comment Manager";
}

<!-- Main content -->

<div class="container-fluid">
    <h3>Comment Management</h3>
    <hr />
    <section>
        <div class="heading mt-2 mb-2">
            <form asp-action="Index" asp-controller="CommentManager" asp-area="Blog" method="get" class="form-inline">
                <div class="form-group">
                    @Html.AntiForgeryToken()
                    <button type="button" class="btn btn-danger" id="delete-all" onclick="deleteAll();"><i class="far fa-trash-alt"></i> Comment</button>
                </div>
                <div class="form-group ml-auto d-flex">
                    <select name="pageSize" id="page-size" class="custom-select mr-2">
                        <option value="10">10</option>
                        <option value="15">15</option>
                        <option value="20">20</option>
                        <option value="30">30</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                    </select>
                    <input type="text" class="form-control mr-2" id="inputSearch" name="searchString"
                           value="@ViewData["CurrentFilter"]" placeholder="Search Comment....">
                    <button type="submit" class=" form-control btn btn-primary bg-custom mr-2">
                        <i class="fas fa-search"></i>
                    </button>
                    <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" class="btn btn-secondary">
                        <i class="fas fa-undo"></i>
                    </a>
                </div>
            </form>
        </div>
        <div class="comment-list">
            <table class="table table-bordered comment-list">
                <thead class="bg-custom text-white rounded">
                    <tr>
                        <th scope="col">
                            <input type="checkbox" id="selected-all" />
                        </th>
                        <th scope="col">
                            <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" asp-route-sortOrder="@ViewData["NameSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Content
                            </a>
                        </th>
                        <th scope="col">
                            <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" asp-route-sortOrder="@ViewData["UsernameSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Username
                            </a>
                        </th>
                        <th scope="col">
                            <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" asp-route-sortOrder="@ViewData["PostTitleSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Post Title
                            </a>
                        </th>
                        <th scope="col" class="d-none d-sm-table-cell">
                            <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" asp-route-sortOrder="@ViewData["CreatedDateSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Approved
                            </a>
                        </th>
                        <th scope="col" class="d-none d-md-table-cell">
                            <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" asp-route-sortOrder="@ViewData["ModifiedDateSortParm"]"
                               asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="text-white">
                                Approved Date
                            </a>
                        </th>
                        <th scope="col">Manage</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var comment in Model)
                    {
                        <tr>
                            <td>
                                <input type="checkbox" name="selectedItems" class="selected-items" value="@comment.Id" />
                            </td>
                            <td class="w-25">
                                <a href="#">@comment.Content</a>
                            </td>
                            <td>
                                <a href="#">@comment.User.UserName</a>
                            </td>
                            <td>
                                <a href="#">@comment.Post.Title</a>
                            </td>
                            <td class="d-none d-sm-table-cell">
                                <a href="#">@comment.Approved</a>
                            </td>
                            <td class="d-none d-md-table-cell">
                                <a href="#">@comment.ApprovedDate.ToShortDateString()</a>
                            </td>
                            <td>
                                <form asp-action="Delete" asp-controller="CommentManager" asp-area="Blog" asp-route-id="@comment.Id" method="post">
                                    <button type="submit" formaction="@Url.Action("Approve", "CommentManager", new {id = comment.Id})"
                                            onclick="return confirm('Are you sure to' + @(comment.Approved ? "unapproved" : "approved") + 'this comment?');"
                                            class="btn btn-danger">
                                        @if (comment.Approved)
                                        {
                                            <i class="fas fa-ban"></i>
                                        }
                                        else
                                        {
                                            <i class="far fa-check-square"></i>
                                        }
                                    </button>
                                    <button type="submit"
                                            onclick="return confirm('Are you sure to delete this comment?');"
                                            class="btn btn-danger">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
            ViewBag.PageRange = 3;
        }

        <div class="paging mb-3">
            <nav aria-label="page-navigation">
                <ul class="pagination justify-content-center">
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog"
                           asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           asp-route-pageIndex="1" asp-route-pageSize="@ViewData["CurrentPageSize"]" class="btn page-link @prevDisabled">
                            <i class="fas fa-fast-backward"></i>
                        </a>
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog"
                           asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           asp-route-pageIndex="@(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1)" asp-route-pageSize="@ViewData["CurrentPageSize"]"
                           class="btn page-link @prevDisabled">
                            <i class="fas fa-backward"></i>
                        </a>
                    </li>

                    @for (int i = 1; i <= Model.TotalPages; i++)
                    {
                        if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                        {
                            <li class="page-item">
                                <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog"
                                   asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                                   asp-route-pageIndex="@i" asp-route-pageSize="@ViewData["CurrentPageSize"]"
                                   class="btn page-link @(i==Model.PageIndex ? "current" : "")">
                                    @i
                                </a>
                            </li>
                        }
                    }
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog"
                           asp-route-sortOrder="@ViewData["CurrentSort"]" asp-route-currentFilter="@ViewData["CurrentFilter"]"
                           asp-route-pageIndex="@(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1)"
                           asp-route-pageSize="@ViewData["CurrentPageSize"]" class="btn page-link @nextDisabled">
                            <i class="fas fa-forward"></i>
                        </a>
                    <li class="page-item">
                        <a asp-action="Index" asp-controller="CommentManager" asp-area="Blog" asp-route-sortOrder="@ViewData["CurrentSort"]"
                           asp-route-currentFilter="@ViewData["CurrentFilter"]" asp-route-pageIndex="@(Model.PageIndex)"
                           asp-route-pageSize="@ViewData["CurrentPageSize"]" class="btn page-link @nextDisabled">
                            <i class="fas fa-fast-forward"></i>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </section>
</div>

<!-- End main content -->

@section Scripts {
    <script>
        // Start - Page size
        var currentPageSize = @ViewData["CurrentPageSize"];
        $('#page-size').val(currentPageSize);
        // End - Page size

        // Start - Select all checkboxes
        $('#selected-all').change(function() {
            $('input:checkbox[class=selected-items]').prop('checked', this.checked);
        });
        // End - Select all checkboxes

        // Start - Enable and disable button
        var checkBoxes = $('tbody .selected-items, th #selected-all');
        checkBoxes.change(function () {
            $('#delete-all').prop('disabled', checkBoxes.filter(':checked').length < 1);
        });
        checkBoxes.change();
        // End - Enable and disable button

        // Start - Function delete all
        function deleteAll() {
            var token = $('input[type=hidden][name=__RequestVerificationToken]', document).val();
            var selectedItems = new Array();

            $('.selected-items:checkbox:checked').each(function() {
                selectedItems.push($(this).val());
            });

            $.ajax({
                url: "@Url.Action("DeleteAll", "CommentManager")",
                type: "POST",
                data: JSON.stringify(selectedItems),
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                headers: { 'RequestVerificationToken': token },
                success: function (result) {
                    console.log(result);
                    $.each(selectedItems, function (key, value) {
                        console.log(value);
                        $('input:checkbox[class=selected-items]').each(function () {
                            console.log($(this));
                            if ($(this).val() == value) {
                                $(this).parent().parent().remove();
                            };
                        })
                        $('#delete-all').prop('disabled', true);
                    });
                },
                error: function(errorMessage) {
                    alert(errorMessage.responseText);
                }
            });
        }
        // End - Function delete all
    </script>
}